name: Java CI with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Build with Maven
      run: mvn -f pdfgeneration/pom.xml clean package

    - name: Build Docker Image
      run: docker build -t pdf-app .

    - name: Save Docker image as artifact
      run: docker save pdf-app > pdf-app.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf-app
        path: pdf-app.tar
